# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none
variables:
  vmImage : 'windows-2019'
  solution: '*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

pool:
  vmImage: $(vmImage)

stages:
- stage: build
  displayName: build and package asp.net solution
  jobs:
    - job: build
      displayName: build
      pool:
        vmImage: $(vmImage)
      steps:
        - task: NuGetToolInstaller@1
        - task: NuGetRestore@1
          inputs:
            solution: $(solution)
            selectOrConfig: 'select'
        - task: VSBuild@1
          displayName: build the solution with vs
          inputs:
            solution: $(solution)
            vsVersion: "17.0"
            configuration: $(buildConfiguration)
            platform: $(buildPlatform)
            msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        - task: PublishBuildArtifacts@1
          displayName: publish the artifact   
          inputs:
            ArtifactName: drop
            PathtoPublish: $(build.artifactStagingDirectory)
        - task: VSTest@2
          displayName: testing
          inputs:
            platform: $(buildPlatform)
            configuration: $(buildConfiguration)

- stage: deploy
  dependsOn: build
  displayName: azure app service deploy 
  jobs:
    - job: deploy
      displayName: deploy job
      steps:
        - task: DownloadBuildArtifacts@1
          displayName: Get package from the artifact
          inputs:
            artifactName: drop
            downloadPath: '$(System.ArtifactsDirectory)'
            buildType: current
            downloadType: single
        - task: AzureRmWebAppDeployment@4
          displayName: deploy to azure app service
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Abonnement Visual Studio Enterprise(14abf4c6-3fa0-47af-b4a5-a7fbf3d5a47c)'
            appType: 'webApp'
            WebAppName: mywebappssh001
            packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
            



        
